export const SIGNIN_LOODING_REQUEST = "SIGNIN_LOODING_REQUEST";
export const SIGNIN_SUCCESS_REQUEST = "SIGNIN_SUCCESS_REQUEST";
export const SIGNIN_FAILURE_REQUEST = "SIGNIN_FAILURE_REQUEST";

export const SIGNUP_LOODING_REQUEST = "SIGNUP_LOODING_REQUEST";
export const SIGNUP_SUCCESS_REQUEST = "SIGNUP_SUCCESS_REQUEST";
export const SIGNUP_FAILURE_REQUEST = "SIGNUP_FAILURE_REQUEST";
export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";

export const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_TERMS_SUCCESS = "GET_TERMS_SUCCESS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_HUB_CITIES_SUCCESS = "GET_HUB_CITIES_SUCCESS";
export const GET_ALL_ADMIN_SUCCESS = "GET_ALL_ADMIN_SUCCESS";
